###

POST  http://192.168.1.95:8080/login
Content-Type: application/json

{
    "email": "aj@gmail.com",
    "password": "keith"
}


###

GET http://192.168.1.95:8080/points/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6Mn0sImlhdCI6MTc3OTUyOTgzMSwiZXhwIjoxNzc5NTI5ODY2fQ.RrfKVvoKalOa2-zjpGigq9z2NqR7tULxWDn3y7YUo40
###
POST http://192.168.1.95:8080/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6Mn0sImlhdCI6MTc3OTUwMjYxMX0.cHQctfSDHAXQnfdrcRht3xRYH2h4bDuuDUZpbRWnRgk"
}